#!/bin/sh
set -eu
IFS="$(printf '%b_' '\n\t ')"
IFS="${IFS%_}"

DIR="${0%/*}"

# shellcheck source=/dev/null
. "${DIR}/../lib/reverso.sh"

echo "Running integration test suite."

printf "pig\\nbear\\nman\\n" |
    reverso |
    diff "${DIR}/fixtures/monster.txt" -
